### ISSUE TITLE
Option to increase sound in settings more

### ISSUE THREAD

**Issue by 4turtlez** [elementary/default-settings#241] opened 2021-07-07 17:28 UTC
There are many videos that are to quiet even at full volume. It would be awesome if there was an option in audio setting to overamplify to 150%.

**Comment by cassidyjames** [comment] 2021-07-07 17:37
Issue templates are provided for a reason; ignoring them makes it harder to triage and ultimately address issues. In the future, please use the issue template, putting the relevant information in the relevant sections.

This issue is a duplicate of https://github.com/elementary/switchboard-plug-sound/issues/68

**Closed by cassidyjames** 2021-07-07 17:37 UTC
