### ISSUE TITLE
Plank fails to start without gsettings schema

### ISSUE THREAD

**Issue by hello-smile6** [elementary/default-settings#267] opened 2022-04-01 04:01 UTC
### What Happened?

I am trying to run the `plank` dock application, but it fails to start without the gsettings schema.

### Steps to Reproduce

1. Install NixOS
2. Install ElementaryOS on NixOS
3. Try to get the desktop environment

### Expected Behavior

I expected everything to work even without additional software.

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
LABEL  filesystem LABEL
   LENGTH  magic string length
     TYPE  superblok type
   OFFSET  magic string offset
    USAGE  type description
   DEVICE  block device name

For more details see wipefs(8).
runner@b4fa72a8bfe0:~/vnc-gnome$ ^C
runner@b4fa72a8bfe0:~/vnc-gnome$ wine64
Usage: wine PROGRAM [ARGUMENTS...]   Run the specified program
       wine --help                   Display this help and exit
       wine --version                Output version information and exit
runner@b4fa72a8bfe0:~/vnc-gnome$ plank
[WARN 03:56:37.858454] [Environment:165] XDG_SESSION_CLASS not set in this environment!
[WARN 03:56:37.858504] [Environment:183] Neither of XDG_SESSION_DESKTOP, XDG_CURRENT_DESKTOP or DESKTOP_SESSION is set in this environment!
[WARN 03:56:37.858538] [Environment:196] XDG_SESSION_TYPE not set in this environment!
[ERROR 03:56:37.866711] [Utils:42] GSettingsSchema 'net.launchpad.plank' not found
Trace/breakpoint trap (core dumped)
runner@b4fa72a8bfe0:~/vnc-gnome$
```

### Hardware Info

1GB RAM, https://vnc-gnome.9pfs.repl.co

**Comment by davidmhewitt** [comment] 2022-04-01 06:22
This is fairly typical of any application that uses gsettings. If the schema is not installed, the application will generally not start or not work properly.

So this sounds like more of a packaging issue or an issue with the way it has been installed.

Is there an official route to report bugs to the NixOS packagers? The elementary team doesn't package things for NixOS, it's a community effort.

**Comment by bobby285271** [comment] 2022-04-01 10:32
Hi, I am one of the Pantheon maintainers on NixOS/nixpkgs.

https://vnc-gnome.9pfs.repl.co/vnc.html is an ubuntu machine and sorry I rarely test Pantheon stuff on non NixOS Pantheon installations these days :crying_cat_face: But I can confirm this issue on NixOS GNOME Xorg and this is only a issue for `pantheon.elementary-dock` but not `plank`.

Looks like this is a duplicate of https://github.com/elementary/dock/issues/140, and the https://github.com/elementary/dock/tree/master is missing an post install script which runs `glib-compile-schemas`.


```py
#!/usr/bin/env python3

import os
import subprocess

schemadir = os.path.join(os.environ['MESON_INSTALL_PREFIX'], 'share', 'glib-2.0', 'schemas')

if not os.environ.get('DESTDIR'):
	print('Compiling gsettings schemas...')
	subprocess.call(['glib-compile-schemas', schemadir])
```



p.s.: Though I subscribe to some of the elementary repositories, it will always be nice to also file an issue to the https://github.com/NixOS/nixpkgs and notify `@NixOS/pantheon`, otherwise this issue can get lost from my in inbox easily :crying_cat_face: 

p.p.s.: Actually I personally don't think it possible to get a working Pantheon desktop on non-NixOS system with Nix since many stuff are made possible with NixOS modules like [this](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/desktop-managers/pantheon.nix), please share with us if you make it possible. :rofl:

**Comment by davidmhewitt** [comment] 2022-04-01 11:00
@bobby285271 Thank you for the info, that should be helpful in the future.

I'll close this issue as a duplicate of https://github.com/elementary/dock/issues/140 and add some more details to that issue about the missing post install script.

**Closed by davidmhewitt** 2022-04-01 11:00 UTC
