### ISSUE TITLE
Allow switching of audio output in volume control in menu bar

### ISSUE THREAD

**Issue by xfbs** [elementary/default-settings#58] opened 2018-04-26 16:14 UTC
Would it be possible to allow users to switch the audio output in the volume control in the menu bar?

#### Background

I have a couple of bluetooth speakers around the house that I like to use. However, sometimes I need to toggle between them and the built-in speaker or headphones. Currently, this is only possible (it seems) from within the settings.

![screenshot from 2018-04-26 18-05-20](https://user-images.githubusercontent.com/786420/39317859-ea920168-497c-11e8-9b06-67389a771525.png)

However, it would be more convenient if it was selectable directly in the volume control in the menu bar.

![screenshot from 2018-04-26 18-04-35](https://user-images.githubusercontent.com/786420/39317885-fd613b42-497c-11e8-8847-4ecefcdc022f.png)

#### Prior Art

On macOS, this is possible by holding down <kbd>alt</kbd> while clicking the volume control. This brings up a more verbose version that allows selecting the audio input and output.

![macOS audio sources](http://media.idownloadblog.com/wp-content/uploads/2015/02/Volume-menu-bar-alt-controls1.png)

I am not familiar how other distros or operating systems solved this issue (or if they addressed it at all).

#### Pledge

I will donate at least $5 if this gets addressed, and I encourage others who would like to see similar functionality to chip in.

**Comment by codygarver** [comment] 2018-04-26 16:16
Thanks for the report but this is a duplicate of an already existing report: elementary/wingpanel-indicator-sound#6

**Closed by codygarver** 2018-04-26 16:16 UTC
