### ISSUE TITLE
Whitelist pantheon-agent-geoclue2

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/default-settings#17] opened 2017-12-28 15:54 UTC
The [GeoClue agent](https://github.com/elementary/pantheon-agent-geoclue2) requires some config file changes in `/etc/geoclue/geoclue.conf` to allow it to act as an agent for the system's location services.

When developing the agent, I was using the debian packaging to make these changes to the config file, but that doesn't seem like the right place, so I've submitted a PR to remove that. See here: https://github.com/elementary/pantheon-agent-geoclue2/pull/16

`/etc/geoclue/geoclue.conf` would need to be like the following to work with the agent (note the whitelist section and the added `io.elementary.desktop.agent-geoclue2` section):
```

# Configuration file for Geoclue

# Agent configuration options
[agent]

# Whitelist of desktop IDs (without .desktop part) of all agents we recognise,
# separated by a ';'.
whitelist=io.elementary.desktop.agent-geoclue2

# Network NMEA source configuration options
[network-nmea]

# Fetch location from NMEA sources on local network?
enable=true

# WiFi source configuration options
[wifi]

# URL to the wifi geolocation service. The key can currenty be anything, just
# needs to be present but that is likely going to change in future.
url=https://location.services.mozilla.com/v1/geolocate?key=geoclue

# To use the Google geolocation service instead of mozilla's, simply uncomment
# this url while changing API_KEY to your Google API key and comment out or
# remove the url above.
#
#url=https://www.googleapis.com/geolocation/v1/geolocate?key=YOUR_KEY

# Submit data to Mozilla Location Service
# If set to true, geoclue will automatically submit network data to Mozilla
# each time it gets a GPS lock.
#
submit-data=false

# URL to submission API of Mozilla Location Service
submission-url=https://location.services.mozilla.com/v1/submit?key=geoclue

# A nickname to submit network data with. This is currently used for leaderboard:
# https://location.services.mozilla.com/leaders
# A nickname must be 2-32 characters long.
submission-nick=geoclue

# Application configuration options
#
# NOTE: Having an entry here for an application with allowed=true means that
#       geoclue will not ask agent to authorize the application. This is to
#       ensure that system components and applications with built-in
#       authorization mechanism (e.g web browsers) do not have to be bound to
#       agents.
#
# Format:
#
# # Desktop ID of application without .desktop part
# [random-app]
#
# # Allowed access to location information?
# allowed=true|false
#
# # Is application a system component?
# system=true|false
#
# # List of UIDs of all users for which this application is allowed location
# # info access, separate by ';'. Keep it empty for allowing it for all users.
# users=

[io.elementary.desktop.agent-geoclue2]
allowed=true
system=true
users=

[epiphany]
allowed=true
system=false
users=

[firefox]
allowed=true
system=false
users=
```

**Comment by danrabbit** [comment] 2018-03-15 19:14
Closing because I can confirm that the geoclue agent now works in the latest builds :)

**Closed by danrabbit** 2018-03-15 19:14 UTC
Labels: Status: Confirmed
